* MAPTEK: Specifications 12-Jun-2024 12:28:20
BEGIN$DEF BREAKDOWN
   NAME_1='blk_model'
   NAME_2='categ_gc'
   NAME_3='categ'
   NAME_4='destination'
   NAME_5='pit_area'
END$DEF BREAKDOWN
BEGIN$DEF GRADE_DENSITY
   NAME='current_density'
   DEFAULT=2.675
END$DEF GRADE_DENSITY
BEGIN$DEF GRADE_1
   NAME='au_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_1
BEGIN$DEF GRADE_2
   NAME='ag_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_2
BEGIN$DEF GRADE_3
   NAME='cu_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_3
BEGIN$DEF GRADE_4
   NAME='s_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_4
BEGIN$DEF GRADE_5
   NAME='s2_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_5
BEGIN$DEF GRADE_6
   NAME='c_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_6
BEGIN$DEF GRADE_7
   NAME='oc_ltp'
   BY_MASS
   IGNORE_UNKNOWN
END$DEF GRADE_7
BEGIN$DEF DEFAULTS
END$DEF DEFAULTS
BEGIN$DEF REGION_1
   NAME='C:\Julio_Solano\02_MODELS\PVORE_2024\07_Engineering\07.1_Shells\Reserve\RESERVE_240531.00t'
   GROUP=' '
END$DEF REGION_1
BEGIN$DEF REGION_2
   NAME='C:\Julio_Solano\02_MODELS\PVORE_2024\07_Engineering\07.1_Shells\Resources\RESOURCE_240531.00t'
   GROUP=' '
END$DEF REGION_2
BEGIN$DEF BLOCKSELECTION
   EXACT_VOLUMES
END$DEF BLOCKSELECTION
BEGIN$DEF blockselection2
   NO_FULL_BLOCKS
   NO_PARTIAL_BLOCKS
END$DEF blockselection2
BEGIN$DEF OutputFilePreference
   NO_DMP
   CSV
   USE_REGION_NAMES
   REGION_FILENAME_FORMAT=0
   NO_UPDATE_TRI_BY_CSV
END$DEF OutputFilePreference
BEGIN$DEF NAME_CONVENTION
   NO_NEW_NAME_CONV
   TRIORDER=' '
   POLORDER=' '
   DELIM=' '
   PITNAME=' '
   PERIOD=0
END$DEF NAME_CONVENTION
BEGIN$DEF CENTRELINES
   LAYER_ORDER=0
   FEATURE_ORDER=0
   GROUP_ORDER=0
   OBJECT_ORDER=0
   LAYER_PREFIX=' '
   FEATURE_PREFIX=' '
   GROUP_PREFIX=' '
   OBJECT_PREFIX=' '
   LAYER_SUFFIX=' '
   FEATURE_SUFFIX=' '
   GROUP_SUFFIX=' '
   OBJECT_SUFFIX=' '
END$DEF CENTRELINES
BEGIN$DEF POLY_SETUP
   NO_BY_BNCH_HGHT
   HEIGHT=0
   NO_TOP
   NO_MIDDLE
   NO_BASE
   NO_ADJUSTMENT
   BEARING=0
   GRADIENT=0
   NO_PROJ_POLY
   NO_BY_PROJECT
   BACK_DIST=0
   FORWARD_DIST=0
   NO_CONFIRM
   NO_DUPLICATE
   NO_DYNANMIC
   LAYER=' '
END$DEF POLY_SETUP
END$FILE
